# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

# Start SSH Agent
echo ">>> SSH Agent"
eval `ssh-agent -s`
# Add private SSH keys
ssh-add ~/.ssh/github
